### ISSUE TITLE
Some user-friendly additions to our data writing functionality

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/dfmodules#21]
A couple of usability improvements in the data-writing part of the MiniDAQApp

1) Add the ability to disable the writing of data to disk

Giovanna has requested that this parameter be associated with the ‘start’ command.  That is, users should be able to enable and disable data-writing at the start of each run, without needing to reconfigure the system.

* I believe that we want this parameter to be associated with the DataWriter module (not the DataStore instance that is used by the DataWriter module).  In this way, *all* interactions with the DataStore instance can be disabled.  Given this, it might be better to name the parameter something like “data-storage-disable”.  (Not ‘disk-writing-disabled’.)

* A question that may come up:  should we even create a DataStore instance?  The answer to this must be “yes”, because the DataStore instance is created at ‘conf’ time, before we know whether data-storage will happen for a given run.

A bonus feature request from Giovanna:  for testing, it would also be cool to add a pre-scaling parameter, such that we may decide to write one event out of x. This is really only for test purposes and very long stability tests that we may want to do in the future, without lowering the rate of all the other data acquisition parts

2) Add unique identifiers to HDF5 filenames so that over-writes of existing files are prevented.

The unique identifiers that have been mentioned so far include a timestamp and a username.

This feature will naturally be part of the HDF5DataStore (not a general characteristics of DataStores, nor of the DataWriter) since it is focused on the names of the HDF5 data files.

We can imagine providing a configuration parameter for disabling this behavior, but it would be enabled by default.  

We’ll need to think about the right format for the timestamp.

3) Check for an invalid output directory or full disk at ‘Start’ time

This should be functionality within the HDF5DataStore.  However, it will need to be activated by a method call from the DataWriter module. It will likely require the addition of a new method in the DataStore interface, something like start_run().  Since some sort of ‘begin-run’ operation might be useful for other types of DataStores, it seems reasonable to add it to the interface.

We should throw an exception that somehow aborts the begin-run transition.

4) Close open files at Stop time

This should be functionality within the HDF5DataStore.  It will likely require the addition of a new method in the DataStore interface, something like stop_run().  Since some sort of ‘end-run’ operation might be useful for other types of DataStores, it seems reasonable to add it to the interface.

**Comment by bieryAtFnal** [comment]
I have started making these changes on a branch in the _dfmodules_ repo.  That branch is based on the Style Guide change branch, so it already has those changes.

**Comment by brettviren** [comment]
>     1. Add the ability to disable the writing of data to disk
> 
> 
> Giovanna has requested that this parameter be associated with the ‘start’ command. That is, users should be able to enable and disable data-writing at the start of each run, without needing to reconfigure the system.

Giovanna and I happened to talk a bit on this topic yesterday and probably some more discussion is needed here.

The general need of some feature of allowing a "heavy weight" `conf` command for "main" configuration and some "light weight" augmentation is I think not what is in question, just how best to implement it.

I question the tacking on of configuration info to the `start` command as it will turn this generic command into something that has a variety of schema.

I think it is better we have a new `conf` like command which explicitly carries this new information.  When we get to defining The Grand FSM, it can take into account when this new command may be accepted and that gives more flexibility than hard-bonding it to `start`.

Until this is hashed out and for the immediate minidaqapp development, I'd suggest adding a `data-storage-disable` (or whatever) flag to the `conf` command of the appropriate module.

>     * A question that may come up:  should we even create a DataStore instance?  The answer to this must be “yes”, because the DataStore instance is created at ‘conf’ time, before we know whether data-storage will happen for a given run.

Technically, module instances are created at `init` time but that doesn't change your conclusion here.  And, since there is no `reinit` nor `fini` if one wants to "re-initialize" it effectively means killing `daq_application` and restarting.  With a restart you could apply a different command set which either does or does not include `DataStore`.

> A bonus feature request from Giovanna: for testing, it would also be cool to add a pre-scaling parameter, such that we may decide to write one event out of x. This is really only for test purposes and very long stability tests that we may want to do in the future, without lowering the rate of all the other data acquisition parts

Personally, I think this is not cool (in its entirety).  Prescaling is a fine thing, but I object to putting it on output.

It seems even in the minidaqapp the proper location to enact prescaling is in the code that forms the "trigger decisions".  This is where it belongs in the full DAQ and implementing it this way now would be just as easy as putting it on output and gets us one step closer to FD behavior.

>     1. Add unique identifiers to HDF5 filenames so that over-writes of existing files are prevented.
> 
> 
> The unique identifiers that have been mentioned so far include a timestamp and a username.
> 
> This feature will naturally be part of the HDF5DataStore (not a general characteristics of DataStores, nor of the DataWriter) since it is focused on the names of the HDF5 data files.
> 
> We can imagine providing a configuration parameter for disabling this behavior, but it would be enabled by default.
> 
> We’ll need to think about the right format for the timestamp.

Just a suggest to consider: a short (eg, something around 8-16 char) hash will be future proof when inevitably we discover a collision with the more semantically meaningful labels.  The hash can be upgraded to use more unique inputs and the breaking file name format convention will not require breakage.

>     1. Close open files at Stop time
> 
> 
> This should be functionality within the HDF5DataStore. It will likely require the addition of a new method in the DataStore interface, something like stop_run(). Since some sort of ‘end-run’ operation might be useful for other types of DataStores, it seems reasonable to add it to the interface

Just my 2c of semantics but `close_files()` or `flush()` or similar seems a better name.  Ie, better to name things by what they do not by how they might be used especially as there are many ways to use them.

**Comment by bieryAtFnal** [comment]
Thanks for the comments.
A few responses...

- I understand that there may be better ways to specify configuration parameters than including them with the Start command.  I look forward to hearing more about those options as the discussions progress, and in the meantime, I'll simply use the Start command for these as a way to make progress on the underlying functionality in the C++ code.
- The prescale option mentioned here is certainly not intended to be used to prescale triggers.  Of course, any such prescaling should happen in the TriggerDecisionEmulator or the more realistic trigger modules that we develop later.  This prescale option is only intended to be used for expert-level system testing in which we want to avoid writing lots of data.  An example scenario might be a long-duration stability test in which we want to include disk-writing in the test (to verify that it works), but we don't want to full up a disk with non-essential data.
- As suggested, I'm considering a hash for helping to make filenames unique.  Related to this, I've received other feedback that human-readable strings have some advantages.  I'll probably prototype both models so that we have them available, and I will talk with Mike Kirby about the advantages of a fixed-length hash.
- I've taken the suggestion to think more about the method names that can be used at Start time and Stop time.  At the moment, I've put in "prepare_for_run(run number)" and "finish_with_run(run number).  I understand the desire to make the method names descriptive of what they do, but I'd like to avoid "close_files" because that operation wouldn't necessarily make sense with a different type of DataStore (e.g. an ObjectStoreDataStore).

**Comment by bieryAtFnal** [comment]
Notes on tests that have been done (and that we may want to include in system testing in the future):

- Start a run and immediately stop it (before any events are processed).  This is to verify that there aren't any Stop operations that accidentally depend on seeing at least one event.
- Create a local, temporary configuration that disables data storage and use it in a test.  Verify that no data is written.  
- Create a local, temporary configuration that sets the data storage prescale to a number greater than one and verify that the appropriate fraction of events are written.
- Create a local, temporary configuration that has a bogus output path and verify that a complaint is raised at Start time
- If a full or nearly full disk is available, configure an output path on that disk and verify that a complaint about insufficient disk space is raised at Start time
- Confirm that the unit tests associated with an invalid output path and insufficient disk space pass

**Comment by bieryAtFnal** [comment]
Some notes on work that still remains to be done:
* (if this is desired) update minidaqapp/python/minidaqapp/fake_app_confgen.py to allow data-writing to be disabled via a coommand-line argument, similar to setting the number of links.  There is an example of how to do this in dfmodules/python/dfmodules/testapp_noreadout_confgen.py.  We can create a separate PR for that in the minidaqapp repo after these changes become generally available in the dfmodules repo.
* write unit tests to check that the invalid-data-path and full-disk tests work correctly in the prepare_for_run() method
* restore the ability to read data and get_all_existing_keys in HDF5DataStore.  This is probably best to include as part of changes to output file handling, such as implementing a file size limit.

**Comment by carloschavez** [comment]
Hi Kurt,

I had a looked at your changes and they  look good to me.
Then I proceed to run the tests, my comments here:

> Notes on tests that have been done (and that we may want to include in system testing in the future):
> 
>     * Start a run and immediately stop it (before any events are processed).  This is to verify that there aren't any Stop operations that accidentally depend on seeing at least one event.

_Checked_ 

> 
>     * Create a local, temporary configuration that disables data storage and use it in a test.  Verify that no data is written.
_Checked_ 
> 
>     * Create a local, temporary configuration that sets the data storage prescale to a number greater than one and verify that the appropriate fraction of events are written.
_Checked_  for prescaled values (1-5)  works well,  however if you input a prescaled value >6 , then the data writer module sends a trigger_inhibit condition to the TriggerEmulator module an a message of "Dataflow is BUSY" is displayed.
The application has to be stop or killed, as sending commands "pause" & "resume" does not help.
  
> 
>     * Create a local, temporary configuration that has a bogus output path and verify that a complaint is raised at Start time
_Checked_ 

> 
>     * If a full or nearly full disk is available, configure an output path on that disk and verify that a complaint about insufficient disk space is raised at Start time.  (One way to hack this test is to set the max_file_size_bytes parameter in the configuration to a huge value.  The test in the code checks to see if there is enough free space on the disk to handle one file, and the expected file size that it uses is max_file_size_bytes...)
_Checked_ with modified default configuration and it works as long as the size of the max_file_size_bytes parameter is not too big. When I used a very big number the error is not triggered, but when I used a value just slightly bigger than the free space of the machine I was using then the error is issued. 
But it took me a while to realize that the problem was that the value that I was using was too big.
We might  consider using an upper limit in the value of this parameter in order to avoid the case I described.
> 
>     * Confirm that data files have unique substrings in them, such as username and timestamp
_Checked and confirmed_  
> 
>     * Create a local, temporary configuration that disables the unique substrings in filenames and use it in a test.  Verify that those substrings are not in the filenames.
_Checked and confirmed_  
> 
>     * Create a local, temporary configuration that A) disables data storage, and B) has a bogus path for writing the data.  Confirm that no ERS Issue is thrown at Start time by running the system and being able to start/stop, etc.  (And, no data file will be produced.)
_Checked and confirmed_ 
> 
>     * Once unit tests are written to verify that the logic to check for an invalid output path and insufficient disk space are written, check that they pass
_unittests not written yet_  
#

**Comment by bieryAtFnal** [comment]
Carlos, thank you very much for running the tests.

I have committed a fix for the prescale/Busy bug.  I tested a prescale value of 8.  Before the fix, I saw the Busy signal generated, exactly as you described.  After the fix, I did not see any Busy signals in ~35 events (of which 5 were written out).

I will think about the issue that you mention with a large max_file_size value...

**Comment by carloschavez** [comment]
Carlos,
I have _checked_ that the prescale/Busy bug is not there anymore. 
I ran 100 triggers with  a prescale of 10 and got  10 events out and no Busy signals.

**Comment by carloschavez** [comment]
The issue with the large max_file_size parameter appeared because the set value used in the configuration had more digits than what a unit64_t can hold.
So the error is issue correctly when the digits of the set value do not exceed 20. 

This triggered a discussion on the ability of moo to constrain the ranges or values of a configuration parameter, for a discussion on this I have opened issue #29

**Comment by bieryAtFnal** [comment]
I added the value of the max_files_size parameter to the TRACE message in the HDF5DataStore code immediately before the test for sufficient free space.  With that message, I see that inputting a number larger than 2^64-1 as the max_file_size gets converted to zero.  
I believe that this is all informational.  And, I agree with Carlos that the right way to deal with this in the short & medium term is to avoid specifying a max_file_size_bytes greater than 2^64.
Given that, I believe that this code is ready to be merged to the _develop_ branch.  However, I'm going to wait a little bit of time before doing that to see if we'd rather merge a different branch first.
