### ISSUE TITLE
Should TPStreamWriter respect --disable-data-storage?

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/dfmodules#233]

**Comment by wesketchum** [comment]
@bieryAtFnal @roland-sipos @eflumerf any discussion on this?

**Comment by bieryAtFnal** [comment]
When I added the TP stream writing, I considered this question and decided that we should just not enable the stream writing (not create the TPStreamWriter module) in situations in which we don't want it.

In contrast...  In the case of the writing of TriggerRecords by the DataWriter module, the thinking behind the --disable-data-storage flag was that we would sometimes want to run performance tests with the DataWriter module present and receiving data but not actually writing data.

If that is also true for TPStreamWriter, we could also change it to respect the --disable-data-storage flag.  The work that this module has to do, outside of writing the TPSets, is receiving them and packaging them up into bundles of the requested size.  That didn't seem like a big deal to me in the past, but maybe we would want to measure the performance of the bundling part without writing the TPSets to disk...

Another difference between the DataWriter and the TPStreamWriter is that the former is responsible for telling the DFO that the processing of a given TR is done.  So, we can't really have a system without a DataWriter.  But, we can have systems without the TPStreamWriter, because it doesn't have any influence on other parts of the system.
